### ISSUE TITLE
singularity guide

### ISSUE THREAD

**Issue by Tcvalenzuela** [cgroza/GraffiTE#1]

**Comment by Tcvalenzuela** [comment]
Hi
the tool looks amazing!.

I'm trying to use it, maybe is my lack of experience with singularity but after downloading and run it as :

`singularity shell -B /srv/public:/srv/public graffite_latest.sif `

I face the problem that I don't know where are the programs.

I tried:
`
Singularity>  run GraffiTE 
bash: run: command not found

Singularity> nextflow run cgroza/GraffiTE  
bash: nextflow: command not found

`
Can you add some translation of the documentation for Nextflow?

Thanks!

**Comment by clemgoub** [comment]
Hi there!

You actually don't need to use the singularity container by yourself, `Nextflow` will take care of it for you =)

- 1. Make sure you have [`Nextflow` installed](https://www.nextflow.io/docs/latest/getstarted.html)
- 2. To use `GraffiTE`, make sure `Nextflow` and `Singularity` are in the path (or loaded as module on the HPC) and run `GraffiTE` with the command:

```
nextflow run cgroza/GraffiTE \
   --assemblies assemblies.csv \
   --TE_library library.fa \
   --reference reference.fa \
   --reads reads.csv
``` 
>It should download and cache the pipeline and the singularity container. It may take a while do download everything at the first time, but then it will be cached and available on the spot.

If for some reasons (for example your compute nodes don't have access to internet, or else,...)  you can 

1. Clone the github repos `git clone https://github.com/cgroza/GraffiTE.git`
2. Pull the singularity image (as you did) `singularity pull --arch amd64 graffite_latest.sif library://clemgoub/graffite/graffite:latest`
3. Use the pipeline with this command:

```
nextflow run <path-to-install>/GraffiTE/main.nf \
   --assemblies assemblies.csv \
   --TE_library library.fa \
   --reference reference.fa \
   --reads reads.csv \
   -with-singularity <your-path>/graffite_latest.sif
```
> `-with-singularity` need to be given with a single `-`, because it is a `Nextflow` override command. You can also set the path to the singularity image in `<your-path>/GraffiTE/nextflow.config` in order to skip this command when you run the pipeline.

Let me know if you need further help!

Cheers,

Clément
