### ISSUE TITLE
Typo L481 of main.nf

### ISSUE THREAD

**Issue by YannBourgeois** [cgroza/GraffiTE#11]
Hi,

While using GraffiTE with Giraffe on a cluster, I ran into a bug that seems to stem from a typo L481 of the main.sf file:

`vg giraffe -t ${graph__align_threads} -Z index/index.giraffe.gbz -m index/index.min -d index/index.dist -i -f ${sample_reads} > ${sample_name}.gam`

I believe graph__align_threads should be graph_align_threads instead.
Thank you for the very nice work :)
All the best,
Yann

**Comment by cgroza** [comment]
Thank you for catching it. Fixed!
