### ISSUE TITLE
GraffiTE ended at repeatmask vcf: Error executing process > 'repeatmask_VCF (1)'  Caused by:   Process `repeatmask_VCF (1)` terminated with an error exit status (255)

### ISSUE THREAD

**Issue by shenmeguimlf** [cgroza/GraffiTE#12]
Hi, I met an error when processing repeatmask:

```
nextflow run .../Software/GraffiTE/main.nf \
   --assemblies assemblies.csv \
   --TE_library Libraries/RepbaseforRepeatMasker.fasta \
   --reference gadMor3.0_shorten.fa \
   --reads reads.csv \
   --cores 16
```

executor >  local (3)
[e6/7ef80e] process > svim_asm (1)       [100%] 1 of 1 ✔
[e6/ad812a] process > survivor_merge     [100%] 1 of 1 ✔
[13/56bd72] process > repeatmask_VCF (1) [  0%] 0 of 1
[-        ] process > tsd_prep           -
[-        ] process > tsd_search         -
[-        ] process > tsd_report         -
[-        ] process > pangenie           -
[-        ] process > merge_VCFs         -
Error executing process > 'repeatmask_VCF (1)'

Caused by:
  Process `repeatmask_VCF (1)` terminated with an error exit status (255)

Command executed:

  repmask_vcf.sh genotypes.vcf genotypes_repmasked.vcf.gz RepbaseForRepeatMasker.fasta
  bcftools view -G genotypes_repmasked.vcf.gz |     awk -v FS=' ' -v OFS='      '     '{if($0 ~ /#CHROM/) {$9 = "FORMAT"; $10 = "ref"; print $0} else if(substr($0, 1, 1) == "#") {print $0} else {$9 = "GT"; $10 = "1|0"; print $0}}' |     awk 'NR==1{print; print "##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">"} NR!=1' |     bcftools view -i 'INFO/total_match_span > 0.80' -o genotypes_repmasked_temp.vcf
  fix_vcf.py --ref gadMor3.0_shorten.fa --vcf_in genotypes_repmasked_temp.vcf --vcf_out genotypes_repmasked_filtered.vcf

Command exit status:
  255

Command output:
    column count: 10
  
  Meta line 260 read in.
  All meta lines processed.
  gt matrix initialized.
  Character matrix gt created.
    Character matrix gt rows: 31290
    Character matrix gt cols: 10
    skip: 0
    nrows: 31290
    row_num: 0
  
  Processed variant 1000
  Processed variant 2000
  Processed variant 3000
  Processed variant 4000
  Processed variant 5000
  Processed variant 6000
  Processed variant 7000
  Processed variant 8000
  Processed variant 9000
  Processed variant 10000
  Processed variant 11000
  Processed variant 12000
  Processed variant 13000
  Processed variant 14000
  Processed variant 15000
  Processed variant 16000
  Processed variant 17000
  Processed variant 18000
  Processed variant 19000
  Processed variant 20000
  Processed variant 21000
  Processed variant 22000
  Processed variant 23000
  Processed variant 24000
  Processed variant 25000
  Processed variant 26000
  Processed variant 27000
  Processed variant 28000
  Processed variant 29000
  Processed variant 30000
  Processed variant 31000
  Processed variant: 31290
  All variants processed
   [1] "CHROM"            "POS"              "qry_id"           "n_hits"          
   [5] "fragmts"          "match_lengths"    "repeat_ids"       "matching_classes"
   [9] "strands"          "RM_id"           
  compute repeat proportion for each SVs...
  Mammalian filters OFF, writing vcf...

Command error:
  Phase 1 : exact matches
  #################################
  85 matches found in non-fuzzy phase
  
  #################################
  4680 elements found without match
  #################################
  
  
  #################################
  Output file should be manually edited to take into account all specificities of the considered organism!
  #################################
  
  Attaching package: 'dplyr'
  
  The following objects are masked from 'package:stats':
  
      filter, lag
  
  The following objects are masked from 'package:base':
  
      intersect, setdiff, setequal, union
  
  
     *****       ***   vcfR   ***       *****
     This is vcfR 1.13.0 
       browseVignettes('vcfR') # Documentation
       citation('vcfR') # Citation
     *****       *****      *****       *****
  
  Warning message:
  The `x` argument of `as_tibble.matrix()` must have unique column names if
  `.name_repair` is omitted as of tibble 2.0.0.
  i Using compatibility `.name_repair`. 
  awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
  mktemp: failed to create file via template '/scratch/SlurmTMP/user.7524169/tmp.XXXXXXXXXX': No such file or directory
  .../Software/GraffiTE/bin/repmask_vcf.sh: line 146: ${HDR_FILE}: ambiguous redirect
  .../Software/GraffiTE/bin/repmask_vcf.sh: line 147: ${HDR_FILE}: ambiguous redirect
  .../Software/GraffiTE/bin/repmask_vcf.sh: line 148: ${HDR_FILE}: ambiguous redirect
  .../Software/GraffiTE/bin/repmask_vcf.sh: line 149: ${HDR_FILE}: ambiguous redirect
  .../Software/GraffiTE/bin/repmask_vcf.sh: line 150: ${HDR_FILE}: ambiguous redirect
  .../Software/GraffiTE/bin/repmask_vcf.sh: line 151: ${HDR_FILE}: ambiguous redirect
  .../Software/GraffiTE/bin/repmask_vcf.sh: line 152: ${HDR_FILE}: ambiguous redirect
  .../Software/GraffiTE/bin/repmask_vcf.sh: line 153: ${HDR_FILE}: ambiguous redirect
  .../Software/GraffiTE/bin/repmask_vcf.sh: line 154: ${HDR_FILE}: ambiguous redirect
  .../Software/GraffiTE/bin/repmask_vcf.sh: line 155: ${HDR_FILE}: ambiguous redirect
  sort: cannot create temporary file in '/scratch/SlurmTMP/user.7524169': No such file or directory
  [E::hts_open_format] Failed to open file "CHROM,POS,~ID,INFO/n_hits,INFO/fragmts,INFO/match_lengths,INFO/repeat_ids,INFO/matching_classes,INFO/RM_hit_strands,INFO/RM_hit_IDs,INFO/total_match_length,INFO/total_match_span" : No such file or directory
  Failed to read from CHROM,POS,~ID,INFO/n_hits,INFO/fragmts,INFO/match_lengths,INFO/repeat_ids,INFO/matching_classes,INFO/RM_hit_strands,INFO/RM_hit_IDs,INFO/total_match_length,INFO/total_match_span: No such file or directory
  Failed to read from standard input: unknown file type

Work dir:
  /.../work/13/56bd72c9c56695ebc011428b61aac4

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

_______________

.command.sh:

`#!/bin/bash -ue
repmask_vcf.sh genotypes.vcf genotypes_repmasked.vcf.gz RepbaseForRepeatMasker.fasta
bcftools view -G genotypes_repmasked.vcf.gz |     awk -v FS='   ' -v OFS='      '     '{if($0 ~ /#CHROM/) {$9 = "FORMAT"; $10 = "ref"; print $0} else if(substr($0, 1, 1) == "#") {print $0} else {$9 = "GT"; $10 = "1|0"; print $0}}' |     awk 'NR==1{print; print "##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">"} NR!=1' |     bcftools view -i 'INFO/total_match_span > 0.80' -o genotypes_repmasked_temp.vcf
fix_vcf.py --ref gadMor3.0_shorten.fa --vcf_in genotypes_repmasked_temp.vcf --vcf_out genotypes_repmasked_filtered.vcf`

**Comment by clemgoub** [comment]
Hi Lingfeng,

The error is caused by the singularity image being unable to reach a writable temporary folder. To solve this, you can try to add the following line to the file `nextflow.config`:

```
singularity.runOptions = '--contain -B ${SLURM_TMPDIR}:/tmp'
```

`${SLURM_TMPDIR}` may not exist on your cluster (this is the default temporary directory variable in our HPC). You can change it to any writable folder the working node can access during the job's run.

Let me know if it fixes the issue, otherwise we'll try something else!

Cheers,

Clément

**Comment by shenmeguimlf** [comment]
Hi Clément,

Thank you for your help and fast response, I hope you are doing well!
I modified nextflow.config and added that line, with added a tmp directory in this work directory as SLURM_TMPDIR in my .bashrc:
`SLURM_TMPDIR=/gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/tmp`
, however, it still reported the same error, just with a bit difference in the end, to see .command.run instead of .command.sh :
---
executor >  local (3)
[1d/2cba19] process > svim_asm (1)       [100%] 1 of 1 ✔
[25/c795c2] process > survivor_merge     [100%] 1 of 1 ✔
[4f/590548] process > repeatmask_VCF (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > tsd_prep           -
[-        ] process > tsd_search         -
[-        ] process > tsd_report         -
[-        ] process > pangenie           -
[-        ] process > merge_VCFs         -
Error executing process > 'repeatmask_VCF (1)'

Caused by:
  Process `repeatmask_VCF (1)` terminated with an error exit status (255)

Command executed:

  repmask_vcf.sh genotypes.vcf genotypes_repmasked.vcf.gz RepbaseForRepeatMasker.fasta
  bcftools view -G genotypes_repmasked.vcf.gz |     awk -v FS=' ' -v OFS='      '     '{if($0 ~ /#CHROM/) {$9 = "FORMAT"; $10 = "ref"; print $0} else if(substr($0, 1, 1) == "#") {print $0} else {$9 = "GT"; $10 = "1|0"; print $0}}' |     awk 'NR==1{print; print "##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">"} NR!=1' |     bcftools view -i 'INFO/total_match_span > 0.80' -o genotypes_repmasked_temp.vcf
  fix_vcf.py --ref gadMor3.0_shorten.fa --vcf_in genotypes_repmasked_temp.vcf --vcf_out genotypes_repmasked_filtered.vcf

Command exit status:
  255

Command output:
    column count: 10
  
  Meta line 260 read in.
  All meta lines processed.
  gt matrix initialized.
  Character matrix gt created.
    Character matrix gt rows: 31290
    Character matrix gt cols: 10
    skip: 0
    nrows: 31290
    row_num: 0
  
  Processed variant 1000
  Processed variant 2000
  Processed variant 3000
  Processed variant 4000
  Processed variant 5000
  Processed variant 6000
  Processed variant 7000
  Processed variant 8000
  Processed variant 9000
  Processed variant 10000
  Processed variant 11000
  Processed variant 12000
  Processed variant 13000
  Processed variant 14000
  Processed variant 15000
  Processed variant 16000
  Processed variant 17000
  Processed variant 18000
  Processed variant 19000
  Processed variant 20000
  Processed variant 21000
  Processed variant 22000
  Processed variant 23000
  Processed variant 24000
  Processed variant 25000
  Processed variant 26000
  Processed variant 27000
  Processed variant 28000
  Processed variant 29000
  Processed variant 30000
  Processed variant 31000
  Processed variant: 31290
  All variants processed
   [1] "CHROM"            "POS"              "qry_id"           "n_hits"          
   [5] "fragmts"          "match_lengths"    "repeat_ids"       "matching_classes"
   [9] "strands"          "RM_id"           
  compute repeat proportion for each SVs...
  Mammalian filters OFF, writing vcf...

Command error:
  Phase 1 : exact matches
  #################################
  85 matches found in non-fuzzy phase
  
  #################################
  4680 elements found without match
  #################################
  
  
  #################################
  Output file should be manually edited to take into account all specificities of the considered organism!
  #################################
  
  Attaching package: 'dplyr'
  
  The following objects are masked from 'package:stats':
  
      filter, lag
  
  The following objects are masked from 'package:base':
  
      intersect, setdiff, setequal, union
  
  
     *****       ***   vcfR   ***       *****
     This is vcfR 1.13.0 
       browseVignettes('vcfR') # Documentation
       citation('vcfR') # Citation
     *****       *****      *****       *****
  
  Warning message:
  The `x` argument of `as_tibble.matrix()` must have unique column names if
  `.name_repair` is omitted as of tibble 2.0.0.
  i Using compatibility `.name_repair`. 
  awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
  mktemp: failed to create file via template '/scratch/SlurmTMP/smomw544.7527934/tmp.XXXXXXXXXX': No such file or directory
  /gxfs_work1/geomar/smomw544/Software/GraffiTE/bin/repmask_vcf.sh: line 146: ${HDR_FILE}: ambiguous redirect
  /gxfs_work1/geomar/smomw544/Software/GraffiTE/bin/repmask_vcf.sh: line 147: ${HDR_FILE}: ambiguous redirect
  /gxfs_work1/geomar/smomw544/Software/GraffiTE/bin/repmask_vcf.sh: line 148: ${HDR_FILE}: ambiguous redirect
  /gxfs_work1/geomar/smomw544/Software/GraffiTE/bin/repmask_vcf.sh: line 149: ${HDR_FILE}: ambiguous redirect
  /gxfs_work1/geomar/smomw544/Software/GraffiTE/bin/repmask_vcf.sh: line 150: ${HDR_FILE}: ambiguous redirect
  /gxfs_work1/geomar/smomw544/Software/GraffiTE/bin/repmask_vcf.sh: line 151: ${HDR_FILE}: ambiguous redirect
  /gxfs_work1/geomar/smomw544/Software/GraffiTE/bin/repmask_vcf.sh: line 152: ${HDR_FILE}: ambiguous redirect
  /gxfs_work1/geomar/smomw544/Software/GraffiTE/bin/repmask_vcf.sh: line 153: ${HDR_FILE}: ambiguous redirect
  /gxfs_work1/geomar/smomw544/Software/GraffiTE/bin/repmask_vcf.sh: line 154: ${HDR_FILE}: ambiguous redirect
  /gxfs_work1/geomar/smomw544/Software/GraffiTE/bin/repmask_vcf.sh: line 155: ${HDR_FILE}: ambiguous redirect
  sort: cannot create temporary file in '/scratch/SlurmTMP/smomw544.7527934': No such file or directory
  [E::hts_open_format] Failed to open file "CHROM,POS,~ID,INFO/n_hits,INFO/fragmts,INFO/match_lengths,INFO/repeat_ids,INFO/matching_classes,INFO/RM_hit_strands,INFO/RM_hit_IDs,INFO/total_match_length,INFO/total_match_span" : No such file or directory
  Failed to read from CHROM,POS,~ID,INFO/n_hits,INFO/fragmts,INFO/match_lengths,INFO/repeat_ids,INFO/matching_classes,INFO/RM_hit_strands,INFO/RM_hit_IDs,INFO/total_match_length,INFO/total_match_span: No such file or directory
  Failed to read from standard input: unknown file type

Work dir:
  /gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/work/4f/590548368dddf115ed6e32641f5b13

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command. run`
---
.command.run:

`#!/bin/bash
# NEXTFLOW TASK: repeatmask_VCF (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_container_env() {
cat << EOF
export PATH="/gxfs_work1/geomar/smomw544/Software/GraffiTE/bin:\$PATH"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/work/4f/590548368dddf115ed6e32641f5b13/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && kill $pid 2>/dev/null
}

nxf_launch() {
    set +u; env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} singularity exec -B /gxfs_work1/geomar/smomw544 -B "$PWD" --contain -B ${SLURM_TMPDIR}:/tmp /gxfs_work1/geomar/smomw544/Software/GraffiTE/graffite_latest.sif /bin/bash -c "cd $PWD; eval $(nxf_container_env); /bin/bash -ue /gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/work/4f/590548368dddf115ed6e32641f5b13/.command.sh"
}

nxf_stage() {
    true
    # stage input files
    rm -f genotypes.vcf
    rm -f RepbaseForRepeatMasker.fasta
    rm -f gadMor3.0_shorten.fa
    ln -s /gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/work/25/c795c2fb0f628fa33da32fb3f8f8ad/svim-asm_variants.vcf genotypes.vcf
    ln -s /gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/Libraries/RepbaseForRepeatMasker.fasta RepbaseForRepeatMasker.fasta
    ln -s /gxfs_work1/geomar/smomw544/FIE/02.MEGAnE/prepared_files/blastdb/mnt/gadMor3.0_shorten.fa gadMor3.0_shorten.fa
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/work/4f/590548368dddf115ed6e32641f5b13/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY`

**Comment by clemgoub** [comment]
Hi Lingfeng,

It is possible that `${SLURM_TMPDIR}` is `/scracth` on the working nodes, even though you have it as `/gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/tmp` in your `.bashrc`. 

Try to directly put `/gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/tmp` in the nextflow.config:

```
singularity.runOptions = '--contain -B /gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/tmp:/tmp'
```

If this doesn't work, I may simply replace the calls to `maketmp` in the scripts (but it would take a little time).

Cheers,

Clément

**Comment by shenmeguimlf** [comment]
Hi Clément,

Thanks for helping me! I tried to put that directory directly inside of the nextflow.config and re-ran the program after deleting the .nextflow.config and .nextflow/ also the running outputs from the first run in the workdir, but unfortunately it still doesn’t work and the error is still about writing permissions :( 

log file:
[graffiTE_kwi.out.secondrun.txt](https://github.com/cgroza/GraffiTE/files/10935932/graffiTE_kwi.out.secondrun.txt)

.command.err:
[command.err.secondrun.txt](https://github.com/cgroza/GraffiTE/files/10935929/command.err.secondrun.txt)

.command.run
[command.run.secondrun.txt](https://github.com/cgroza/GraffiTE/files/10935966/command.run.secondrun.txt)

In case you need it our HPC system is Red Hat Enterprose Linux 8.2 (other info can be found in https://www.rz.uni-kiel.de/en/our-portfolio/hiperf/nesh), I understand modifying the scripts will take some time, no need to hurry at all :)

Cheers,
Lingfeng

**Comment by clemgoub** [comment]
I'm so sorry about this.

I suggest 3 things before I'll touch on the code:
- 1. Try with `singularity.runOptions = '--contain -B ${TMPDIR}:/tmp'` According to the documentation of your cluster, `$TMPDIR` is the node's variable indicating where to write temporary files. Perhaps `/gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/tmp` is not accessible from a compute node.
- 2. Try again but using an interactive queue on the cluster.
- 3. If both fail, I suggest that you ask support from your IT personnel. I would send off this conversation which should have all the information needed. (I'll be happy to answer any question they may have).

Finally, when you retry, you can add the `-resume` flag (with a single `-`). This will skip the alignment step to save time, if you did not remove the `./work` directory. 

Let me know! We will find a way!

Cheers,

Clément

**Comment by coevolutionlab** [comment]
> I'm so sorry about this.
> 
> I suggest 3 things before I'll touch on the code:
> 
>     * 1. Try with `singularity.runOptions = '--contain -B ${TMPDIR}:/tmp'` According to the documentation of your cluster, `$TMPDIR` is the node's variable indicating where to write temporary files. Perhaps `/gxfs_work1/geomar/smomw544/FIE/07.GraffiTE/cod_Kwi/tmp` is not accessible from a compute node.
> 
>     * 2. Try again but using an interactive queue on the cluster.
> 
>     * 3. If both fail, I suggest that you ask support from your IT personnel. I would send off this conversation which should have all the information needed. (I'll be happy to answer any question they may have).
> 
> 
> Finally, when you retry, you can add the `-resume` flag (with a single `-`). This will skip the alignment step to save time, if you did not remove the `./work` directory.
> 
> Let me know! We will find a way!
> 
> Cheers,
> 
> Clément

Hi Clément,
A slight minor tweak that worked for me was:
I added my singularity_tmpdir in my bashrc and then (since nextflow has problem getting to bashrc for some reason), I modified nextflow.config with following lines:
```
singularity.runOptions = '--contain -B $SINGULARITY_TMPDIR:/tmp'
singularity.envWhitelist = ['SINGULARITY_TMPDIR']
```
With this now, my tmp is set where I want it to be.

I hope it helps!
Best,
Gautam

**Comment by clemgoub** [comment]
Hello Gautam! Thanks for sharing your tip! I had no idea, but this looks line a nice solution! 

@shenmeguimlf, let me know if your issue has been resolved (I wont close the thread until then).

Cheers,

Clément

**Comment by shenmeguimlf** [comment]
Hi Clément,

Thanks for your suggestions! I tried the first two options on last Friday, and it still didn't work and I wrote to our HPC support, and Karsten replied today:

> The origin of the problem is that the pipeline internally uses the command "mktemp" which expects completely open permissions on the directory, where it creates temporary files or directories. Moreover, the command also directly accepts the variable $TMPDIR for the location of this open directory. The latter denotes a problem, because the batch system allows access on $TMPDIR only for the respective user.

> Thus, the only possibility to circumvent this problem is to unset the $TMPDIR variable at the beginning of your batch script, i.e. before the nextflow pipeline is started (note the pitfall: the following command has no '$' sign!):

> unset TMPDIR
> nextflow run ...

> However, you nevertheless want to bind the /tmp directory available inside the singularity container (and having the correct permissions) to a suitable location outside the container. As $TMPDIR is no longer available, you have to do it in this way in your nextflow.config file:

> singularity.runOptions = '--contain -B /scratch/SlurmTMP/${USER}.${SLURM_JOBID}:/tmp'

And I submitted the task again with her suggestions, the initial issue has gone and the pipeline is running smoothly now (Cheers👏 thanks for Gautam's advice 👍) ,  the thread can be closed now.

Thanks so much for your time and helpful suggestions, I will look into the results and hope we can keep in touch later :)

Cheers,
Lingfeng

**Comment by clemgoub** [comment]
Fantastic! 

You can thank Karsten for me, and thanks again Gautam! This thread will be very useful for future users, and I think eventually we'll fix this call to mktemp that creates the issues.

Cheers,

Clément

**Comment by coevolutionlab** [comment]
@clemgoub and @shenmeguimlf Great to hear that!!!
Cheers,
Gautam
