### ISSUE TITLE
singularity issue

### ISSUE THREAD

**Issue by Spieler2999** [cgroza/GraffiTE#13]
I am trying to get GraffiTE installed on our server, but I am having some issues with singularity. I am not sure if this is on my side and I need to update something? I can clone the github repository and all files are downloaded. When I then do the second step I get an error:

singularity pull --arch amd64 graffite_latest.sif library://cgroza/collection/graffite:latest

FATAL: Unable to get library client configuration: remote has no library client (see https://apptainer.org/docs/user/latest/endpoint.html#no-default-remote)

**Comment by cgroza** [comment]
Hello,

I just ran the same command on our server and it works.
It appears to be due to a difference in the configuration of singularity (now apptainer).
Could you include the singularity version you are using?

**Comment by cgroza** [comment]
We did some research, and it's related to some new defaults in the latest Apptainer/Singularity versions:

Please run these two commands before trying to pull the image:

```
apptainer remote add --no-login SylabsCloud cloud.sycloud.io
apptainer remote use SylabsCloud
apptainer pull --arch amd64 graffite_latest.sif library://cgroza/collection/graffite:latest
```
Thank you for bringing these new changes to our attention, we are updating our documentation.

Please see here for a video tutorial:
https://hsf-training.github.io/hsf-training-singularity-webpage/02-running-containers/index.html

**Comment by Spieler2999** [comment]
Hi,
Many thanks for fixing the problem so fast!
 
I could run it with the test data that was provided (see command below). I get 3 folders as output:1_SV_search   2_Repeat_Filtering   3_TSD_search

However, when I change the --genotype false  to --genotype true, to get the 4th genotype folder then I get an error:

No such file: /home/mnilsson/GraffiTE/reads.fq
 -- Check script 'main.nf' at line: 390 or see '.nextflow.log' file for more details

Not sure what I need to change to do the genotyping with the test data?


NXF_VER=20.10.0 nextflow run /home/mnilsson/GraffiTE/main.nf 
--assemblies /home/mnilsson/GraffiTE/test/GraffiTE_testset/assemblies.csv
--reference /home/mnilsson/GraffiTE/test/GraffiTE_testset/hs37d5.chr22.fa
--TE_library /home/mnilsson/GraffiTE/test/GraffiTE_testset/human_DFAM3.6.fasta 
--out testFolder 
--mammal 
--genotype false 
--cpu 2 
-with-singularity /home/mnilsson/GraffiTE/graffite_latest.sif

**Comment by clemgoub** [comment]
Hello!

I'm happy Cristian's fix worked well! Perfect! Now let's see this next issue =)

I think you simply need to add the read input table with `--reads <read_input_table.csv>`. In the current command, only the assemblies are provided for SV search, but no `--reads` are present for genotyping.

Also, but this is not critical: when genotyping you don't need to specify `--genotype true`, it will do it by default. However, the read input table is needed.

```
NXF_VER=20.10.0 nextflow run /home/mnilsson/GraffiTE/main.nf
--assemblies /home/mnilsson/GraffiTE/test/GraffiTE_testset/assemblies.csv
--reference /home/mnilsson/GraffiTE/test/GraffiTE_testset/hs37d5.chr22.fa
--TE_library /home/mnilsson/GraffiTE/test/GraffiTE_testset/human_DFAM3.6.fasta
--reads /home/mnilsson/GraffiTE/test/GraffiTE_testset/reads.csv
--out testFolder
--mammal
--cpu 2
-with-singularity /home/mnilsson/GraffiTE/graffite_latest.sif
```

One last thing: Cristian updated the repos yesterday, and normally, the flag `NXF_VER=20.10.0 ` is not needed anymore (make sure you pull the repos before). Let us know if that works =)

**Comment by Spieler2999** [comment]
Hi, 
I added the --reads reads.csv and it worked without problems.

I installed GraffiTE again (29.06.2023) and this time I could run without the NXF_VER=20.10.0.

So the installation and test data is running exactly as it should. I will now try with my own data :)

Many thanks!
