### ISSUE TITLE
Error for PanGenie-index

### ISSUE THREAD

**Issue by dtx282000** [cgroza/GraffiTE#19]
Description:

I'm encountering an issue when running the following command:

PanGenie-index -v pangenome.vcf -r GXFZ.fa -t 8 -o pangenome

The error message I'm receiving is:
https://private-user-images.githubusercontent.com/24269804/300379928-55105a77-470e-4216-91e5-1ca02ff4decc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDE2NDUsIm5iZiI6MTcwNjU0MTM0NSwicGF0aCI6Ii8yNDI2OTgwNC8zMDAzNzk5MjgtNTUxMDVhNzctNDcwZS00MjE2LTkxZTUtMWNhMDJmZjRkZWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE1MTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYWJlMjBiMGI5NDk3ZmNiMjZlMDJlZWQwNmExOWUyMTEyMzc0YjAwYjRhNjIxMmFkYjUxMzRhOWJmYzg4MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6O0tLJA1oM935GJ4ROz_T3uzJdwk_EUcIUnI7bZajtU
https://private-user-images.githubusercontent.com/24269804/300379990-e6160b36-8c80-47d0-9d81-4b50561d0384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDE2NDUsIm5iZiI6MTcwNjU0MTM0NSwicGF0aCI6Ii8yNDI2OTgwNC8zMDAzNzk5OTAtZTYxNjBiMzYtOGM4MC00N2QwLTlkODEtNGI1MDU2MWQwMzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE1MTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZjkxNTg3ODAwMDEwY2JiNmY1NjYzYTYxZDVhZGQ3ZTRhZTU2OWQ2MjVmZDc5ZjM5OGIzYzM2ZmU0OTc2ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jf80qTBPsT8JxUS1JpKwPh7A2tOk7GanTxhVG45ELbA

Here, pangenome.vcf file is as follows:

https://private-user-images.githubusercontent.com/24269804/300380587-ec64c1fc-1f47-4ba3-8a62-4f4d61cd7c92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDE2NDUsIm5iZiI6MTcwNjU0MTM0NSwicGF0aCI6Ii8yNDI2OTgwNC8zMDAzODA1ODctZWM2NGMxZmMtMWY0Ny00YmEzLThhNjItNGY0ZDYxY2Q3YzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE1MTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MTVmYjM2ZWU2NmIyYzg2NjU4Y2ZkMDRjNzgzMTUzNTIyYWE0ZGZlOGNiOTllZmQwMWVmODAzYzQ5NzdjNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0P-sdiE4-iXqQeCUTSNVhW1QCyfR28Hu4bhVGuPgL1E

So, how can I handle it?

**Comment by dtx282000** [comment]
Thanks! I have solved it.

**Comment by clemgoub** [comment]
Thank you! If you have the time, I'd be curious to know what was the issue. This could help other users! Cheers!
