### ISSUE TITLE
does GraffiTE work with 10x linked reads?   

### ISSUE THREAD

**Issue by Lin-Yuying** [cgroza/GraffiTE#29]
Hi there,

Thank you so much for developing such a good tool to identify the polymorphic TEs. 

I am wondering if GraffiTE can work with 10x linked reads? The contig-levle assembly of 10x linked reads is much shorter than the PacBio/Nanopore and might not be able to have contigs spanning highly repetitive regions. Given these, do you think GraffiTE can work with the contig level assembly from 10x linked read data?

Thanks in advance!

Best,
Lin

**Comment by clemgoub** [comment]
Hello Lin-Yuning

Technically, the program should be able to work with you assemblies, even if they are based on 10X reads. SVIM-asm, the program that makes the SV calls from the the assembly-to-reference mapping was developed for long-read assemblies, so it is possible that the performance may not be the best (it may miss several insertions compared to long-read based assemblies), but it's worth a try.

Let us know what you think of the results!

Cheers,

Clément
