### ISSUE TITLE
Singularity issue

### ISSUE THREAD

**Issue by qizhengyang2017** [cgroza/GraffiTE#34]
I used the singularity (3.8.6)
When I ran the code
```
singularity remote add --no-login SylabsCloud cloud.sycloud.io
singularity remote use SylabsCloud
```
An error occurred
```
FATAL:   name collision while syncing: SylabsCloud
```
How can I solve it?

**Comment by cgroza** [comment]
We also have a docker image now.

Just pull from the Docker:

singularity pull docker://cgroza/graffite

**Comment by qizhengyang2017** [comment]
Thank you for your reply. 
I found I didn't need to run these two commands. And then I can pull the image successfully.

**Comment by qizhengyang2017** [comment]
Another question is that my short reads are paired-ends. So I have two files for one sample. How can I edit the reads.csv? 

here is the content of the reads.csv in the package:
```
path,sample
HG002.100k.set1.Illumina.fastq.gz,short_test1
```

**Comment by cgroza** [comment]
Right now you must make them into an interleaved FASTQ.

Cristian Groza

-------- Original Message --------

**Comment by qizhengyang2017** [comment]
Could you tell me how can I only run step1, step2 and step3?

**Comment by cgroza** [comment]
So you want to do discovery and annotation of TEs, but not alignment of reads?

In this case, pass --assemblies, --TE_library, and --reference
But to skip the rest, pass -- genotype false.

-------- Original Message --------
On 7/26/24 8:47 AM, qizhengyang2017 wrote:
Could you tell me how can I only run step1, step2 and step3?

**Comment by qizhengyang2017** [comment]
Thank you very much!
