### ISSUE TITLE
FATAL: Extraction failed (cache disk quote issue)

### ISSUE THREAD

**Issue by TobyBaril** [cgroza/GraffiTE#37]
Hi! 

I'm pretty new to singularity and apptainer so maybe this is something quite simple. I'm getting the following error for my run:
```
FATAL:   while extracting /data/toby/troutGenomics/graffite_parameters/work/singularity/cgroza-collection-graffite-latest.img: root filesystem extraction failed: failed to copy content in staging file: write /tmp/rootfs-1132018289/archive-4076445747: disk quota exceeded
```

I think this is to do with the cache directory. I've tried to set this by setting the variables: `NXF_APPTAINER_CACHEDIR=/data/toby/tmp/` and `SINGULARITY_CACHEDIR=/data/toby/tmp/` but I'm still getting the same error. Is there a way to change the cache directory so I can get this to run?

Thanks!

**Comment by clemgoub** [comment]
Hi Toby! 

Do you get this after running the command directly on a compute node? Maybe try to follow [these instructions](https://github.com/cgroza/GraffiTE#running-graffite) ("If using from a local apptainer image and with a clone of the Github repository:") to directly download the image while on a login node, and then run GraffiTE on a compute node with the flag `-with-singularity <imagePath>`. 

Did you also try [modifying Nextflow's config file](https://github.com/cgroza/GraffiTE#important-note)? This is usually how I solve my tmpdir issues!

Let us know, and maybe @cgroza will be also able to chime in!

Cheers,

Clément

**Comment by TobyBaril** [comment]
Thanks Clément! 

I should've read more into the docs! I've altered the `/tmp` binding - but in my case `squashfuse` was actually missing and needed to be installed (weird...always thought it came with singularity!). Most likely just a weird thing on our server here!

Cheers!

**Comment by TobyBaril** [comment]
Okay I've got further - now stopping with the following:

```
Process `survivor_merge` input file name collision  -- There are multiple input files for each of the following file names: null.vcf
```
