### ISSUE TITLE
repmask_vcf.sh creating empty indels.fa file (longreads run ending at tsd_prep)

### ISSUE THREAD

**Issue by tiagonardi** [cgroza/GraffiTE#39]
TL,DR: (hopefully) fixed by reverting this commit https://github.com/cgroza/GraffiTE/commit/6a9bdc626006fd3fc4bc01f2e1057e0a1fe70596 

Hi, 
I ran graffiTE in GT-sn-GA mode, with 2 samples.
The run was launched with the command:
`nextflow run cgroza/GraffiTE \
   --longreads longreads.csv \
   --TE_library TE_hsa_library.fasta \
   --reference hs1.fa \
   --graph_method graphaligner \
   --mammal \
   --reads longreads.csv \
   --cores 20 \
   --aligner minimap2`
Using the apptainer image, pulled with
`apptainer pull --arch amd64 graffite_latest.sif library://cgroza/collection/graffite:latest`
The run ended after tsd_prep step, marked as complete. I checked if it was the usual /tmp folder issue, but that wasn't the case.
Looking in the work directories I found that during the repeatmask_VCF process repmask_vcf.sh made an empty indels.fa file.
I tried the bcftools commands inside repmask_vcf.sh with sniffles2_variants.vcf:
`bcftools view --types indels --include 'ILEN>0' ${VCF} 
bcftools view --types indels --include 'ILEN<0' ${VCF}`
Effectively getting an empty vcf. 
After finding this commit https://github.com/cgroza/GraffiTE/commit/6a9bdc626006fd3fc4bc01f2e1057e0a1fe70596 I modified the two lines of code, using the previous version, and resumed the run restarting from repeatmask_VCF. It seems to do the trick, the resumed run is still ongoing, currently at graph_align_reads.

**Comment by cgroza** [comment]
It's very odd that `bcftools view` skips all the variants. Did you look at the VCF, is there something wrong with the formatting?

-------- Original Message --------

**Comment by tiagonardi** [comment]
Yes: the vcf generated by sniffles in the pipeline reports a N instead of the reference base in REF (insertion) / ALT (deletion) , so bcftools doesn't recognise the rows as deletion/insertion. So, using 
`bcftools view --types other --include 'ILEN<0' `
works.
Using the last version of sniffles (2.4) with the same command used in graffiTE I get a functional vcf.
The version inside graffite_latest.sif is the 2.0.7. Not sure if it's intended or not, but I just checked at https://cloud.sycloud.io/library/cgroza/collection/graffite
and graffite_latest is dated at Jan 20, 2023, and the 2 other images are more recent. Also, one of the other is the version with winnowmap that is not present in graffite_latest.sif

**Comment by cgroza** [comment]
Thank you for bringing this up, we will update the image.

-------- Original Message --------
