### ISSUE TITLE
Update minimap2 to allow lr:hq mode

### ISSUE THREAD

**Issue by annabel-NZ** [cgroza/GraffiTE#45]
Hello, 
I wanted to ask if you would consider a build with an updated version of minimap2 (>2.27).  This supports the lr:hq mapping mode which is most appropriate for the current iteration of ONT reads and would significantly speed up, and quite probably also improve, the long read mappings. 

Many thanks!

**Comment by cgroza** [comment]
Hi

I will update minimap2 and update you here.

-------- Original Message --------

**Comment by annabel-NZ** [comment]
Wonderful. Thank you for being so responsive.

**Comment by cgroza** [comment]
I updated the images and the pipeline to support the `lr:hq` mode. It can now be specified  in the type field just like `pb,ont,hifi`.
