### ISSUE TITLE
Output read-names supporting the individual inserts (and deletions) per sample

### ISSUE THREAD

**Issue by natenstuff** [cgroza/GraffiTE#48]
Hi Cristian,

Please forgive me if I missed it, but is there a way to also output the readNames of the supporting reads per insert and sample in the output VCFs?

This would be quite helpful for validations, and methylation analyses.

Best,
Nathan

**Comment by cgroza** [comment]
Hi! We did think about this feature but is not included to date.
Currently, you can recapitulate this information by aligning the reads to the graph produced by GraffiTE.
Once you have the alignments, you can parse the alignments and look for those that overlap with the nodes associated with the variants.

Cristian

**Comment by natenstuff** [comment]
I'll give it a go, thank you!
